# =============================================================================
# bundle_outputs.R
# -----------------------------------------------------------------------------
# EN: Consolidates the pipeline outputs so the whole repository stays under 100
#     files, which is the maximum the GitHub web uploader accepts in one
#     drag-and-drop.
#
#     Run automatically at the end of run_all.R, or on its own:
#         Rscript scripts/bundle_outputs.R
#
#     What it does:
#       * merges every English LaTeX table into tables_en.tex and every Spanish
#         one into tables_es.tex, then deletes the fragments (54 files -> 2);
#       * merges the per-step sessionInfo files into session_info.txt (9 -> 1);
#       * deletes the PNG copies of the figures, keeping the PDF vector version
#         that a journal needs (40 -> 20).
#
#     Nothing is lost: every deleted file is regenerated by re-running the
#     pipeline, and the merged files contain the identical content.
#
# ES: Consolida las salidas del pipeline para que todo el repositorio quede bajo
#     100 archivos, que es el maximo que acepta el uploader web de GitHub en un
#     solo arrastrar-y-soltar.
#
#     Corre automaticamente al final de run_all.R, o por si solo:
#         Rscript scripts/bundle_outputs.R
#
#     Que hace:
#       * junta cada tabla LaTeX en ingles en tables_en.tex y cada una en espanol
#         en tables_es.tex, y despues borra los fragmentos (54 archivos -> 2);
#       * junta los sessionInfo por paso en session_info.txt (9 -> 1);
#       * borra las copias PNG de las figuras, conservando la version vectorial
#         en PDF que necesita una revista (40 -> 20).
#
#     No se pierde nada: todo archivo borrado se regenera volviendo a correr el
#     pipeline, y los archivos unificados tienen el contenido identico.
# =============================================================================

source("R/00_config.R")

log_msg("bundle_outputs: start")

# -----------------------------------------------------------------------------
# 1. LaTeX tables -> one file per language
# -----------------------------------------------------------------------------

bundle_latex <- function(lang, title_en, title_es) {

  pattern   <- paste0("_", lang, "\\.tex$")
  fragments <- sort(list.files(PATHS$tables, pattern = pattern, full.names = TRUE))
  master    <- file.path(PATHS$tables, paste0("tables_", lang, ".tex"))

  # Never fold a previous master into itself.
  fragments <- setdiff(fragments, master)
  if (length(fragments) == 0) {
    log_msg("  no ", lang, " table fragments to bundle")
    return(invisible(0L))
  }

  header <- c(
    "% ===========================================================================",
    paste0("% ", if (lang == "en") title_en else title_es),
    paste0("% ", format(Sys.time(), "%Y-%m-%d %H:%M:%S")),
    "%",
    if (lang == "en") {
      c("% Every table produced by the pipeline, in one file. Requires",
        "% \\usepackage{booktabs} in the preamble. Include with \\input{tables_en}",
        "% or copy individual table environments into the manuscript.")
    } else {
      c("% Todas las tablas producidas por el pipeline, en un archivo. Requiere",
        "% \\usepackage{booktabs} en el preambulo. Incluir con \\input{tables_es}",
        "% o copiar entornos de tabla individuales al manuscrito.")
    },
    "% ===========================================================================",
    ""
  )

  body <- unlist(lapply(fragments, function(f) {
    name <- sub(paste0("_", lang, "\\.tex$"), "", basename(f))
    c(paste0("% ---- ", name, " ", strrep("-", max(0, 60 - nchar(name)))),
      readLines(f, warn = FALSE),
      "")
  }))

  con <- file(master, open = "wt", encoding = "UTF-8")
  writeLines(c(header, body), con)
  close(con)

  file.remove(fragments)
  log_msg("  ", length(fragments), " ", lang, " tables -> ", basename(master))
  invisible(length(fragments))
}

bundle_latex("en",
             "Papelucho text mining: all tables (English)",
             "Papelucho text mining: todas las tablas (ingles)")
bundle_latex("es",
             "Papelucho text mining: all tables (Spanish)",
             "Papelucho text mining: todas las tablas (espanol)")

# -----------------------------------------------------------------------------
# 2. Session info -> one file
# -----------------------------------------------------------------------------

sess <- sort(list.files(PATHS$logs, pattern = "^sessionInfo_.*\\.txt$",
                        full.names = TRUE))
if (length(sess) > 0) {
  master <- file.path(PATHS$logs, "session_info.txt")
  body <- unlist(lapply(sess, function(f) {
    c(strrep("=", 76), readLines(f, warn = FALSE), "")
  }))
  con <- file(master, open = "wt", encoding = "UTF-8")
  writeLines(c(
    "Software environment for every pipeline step.",
    "Entorno de software de cada paso del pipeline.",
    ""
  ), con)
  writeLines(body, con)
  close(con)
  file.remove(sess)
  log_msg("  ", length(sess), " sessionInfo files -> session_info.txt")
}

# -----------------------------------------------------------------------------
# 3. Figures: keep PDF, drop PNG
# -----------------------------------------------------------------------------
# EN: The PDF is vector and is what a journal requires. The PNG was only ever a
#     convenience preview and is regenerated by setting png = TRUE in
#     save_figure().
# ES: El PDF es vectorial y es lo que exige una revista. El PNG era solo una
#     vista previa de conveniencia y se regenera poniendo png = TRUE en
#     save_figure().

pngs <- list.files(PATHS$figures, pattern = "\\.png$", full.names = TRUE)
if (length(pngs) > 0) {
  file.remove(pngs)
  log_msg("  removed ", length(pngs), " PNG previews, kept the PDF versions")
}

# -----------------------------------------------------------------------------
# 4. Drop intermediates that the pipeline regenerates from what it keeps
# -----------------------------------------------------------------------------
# EN: These four tables are per-replicate or per-token dumps used to build the
#     summaries that are kept. The raw author-draw file alone is 1.7 MB of 6,800
#     rows. Nothing in the paper cites them, and re-running the relevant step
#     regenerates them, so they are removed to leave headroom under the file
#     limit. Deleting this block keeps them.
# ES: Estas cuatro tablas son volcados por replica o por token que sirven para
#     construir los resumenes que si se conservan. El archivo crudo de sorteos por
#     autor solo pesa 1,7 MB con 6.800 filas. Nada del paper los cita, y volver a
#     correr el paso correspondiente los regenera, asi que se eliminan para dejar
#     margen bajo el limite de archivos. Borrar este bloque los conserva.

INTERMEDIATE <- c(
  "09_author_draws_raw.csv",        # 200 draws x 34 metrics, summarised in 09_sensitivity_author_draws
  "04_pos_counts_long.csv",         # per-category counts, summarised in 04_pos_by_book
  "02_lexical_replicate_summary.csv", # per-replicate means and SDs, summarised in 02_lexical_by_book
  "05_narrative_arc_by_book.csv"    # 20 segments x 75 books, plotted in 05_narrative_arc
)

dropped <- 0L
for (f in INTERMEDIATE) {
  path <- file.path(PATHS$tables, f)
  if (file.exists(path)) {
    file.remove(path)
    dropped <- dropped + 1L
  }
}
if (dropped > 0) {
  log_msg("  removed ", dropped, " per-replicate intermediate table(s); ",
          "re-run the relevant step to regenerate")
}

# -----------------------------------------------------------------------------
# 5. Remove .gitkeep from directories that now hold real files
# -----------------------------------------------------------------------------
# EN: A .gitkeep only exists to make git track an empty directory. Once the
#     directory has content it is dead weight against the file limit.
# ES: Un .gitkeep solo existe para que git registre un directorio vacio. Una vez
#     que el directorio tiene contenido, es peso muerto contra el limite.

for (d in c(PATHS$tables, PATHS$figures, PATHS$logs)) {
  keep <- file.path(d, ".gitkeep")
  if (file.exists(keep) && length(list.files(d)) > 1) file.remove(keep)
}

# -----------------------------------------------------------------------------
# 6. Report the resulting file count
# -----------------------------------------------------------------------------

count_files <- function(path, pattern = NULL) {
  length(list.files(path, pattern = pattern, recursive = TRUE))
}

n_code    <- length(list.files("R", pattern = "\\.R$")) +
             length(list.files("scripts", pattern = "\\.R$")) + 1L
n_docs    <- length(list.files(".", pattern = "\\.md$")) +
             length(list.files("docs", pattern = "\\.md$")) + 2L
n_meta    <- count_files(PATHS$metadata)
# The packed corpus, when it is being distributed, is one more tracked file.
n_corpus  <- as.integer(file.exists(file.path("data", "raw", "corpus.tar.gz")))
n_tables  <- count_files(PATHS$tables)
n_figures <- count_files(PATHS$figures)
n_logs    <- count_files(PATHS$logs)
n_keep    <- length(list.files(".", pattern = "^\\.gitkeep$",
                               recursive = TRUE, all.files = TRUE))

total <- n_code + n_docs + n_meta + n_corpus + n_tables + n_figures + n_logs + n_keep

log_msg("  repository file count:")
message(sprintf("    code (R + run_all)   %3d", n_code))
message(sprintf("    docs + README + etc  %3d", n_docs))
message(sprintf("    corpus metadata      %3d", n_meta))
message(sprintf("    outputs/tables       %3d", n_tables))
message(sprintf("    outputs/figures      %3d", n_figures))
message(sprintf("    outputs/logs         %3d", n_logs))
message(sprintf("    .gitkeep             %3d", n_keep))
message(sprintf("    %-20s %3d", "TOTAL", total))

if (total >= 100) {
  message("\n  WARNING: ", total, " files, at or above the 100-file limit of the ",
          "GitHub web uploader. Push from the command line, or drop the ",
          "diagnostic CSVs listed in the README.")
} else {
  message("\n  ", total, " files, under the 100-file limit of the GitHub web uploader.")
}

log_msg("bundle_outputs: done")
